version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/gakkenid
      - ./pkg:/usr/local/bundle
    environment:
      - LANG=ja_JP.UTF-8
      - LC_CTYPE=ja_JP.UTF-8
      - GID_SERVICE_CODE=${GID_SERVICE_CODE}
      - GID_CLIENT_SECRET_TOKEN=${GID_CLIENT_SECRET_TOKEN}
      - GID_ADMIN_ACCESS_TOKEN=${GID_ADMIN_ACCESS_TOKEN}
